// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: bistream/bistream.proto

package bistream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoubleStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *DoubleStreamRequest) Reset() {
	*x = DoubleStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bistream_bistream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleStreamRequest) ProtoMessage() {}

func (x *DoubleStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bistream_bistream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleStreamRequest.ProtoReflect.Descriptor instead.
func (*DoubleStreamRequest) Descriptor() ([]byte, []int) {
	return file_bistream_bistream_proto_rawDescGZIP(), []int{0}
}

func (x *DoubleStreamRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type DoubleStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Num     int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Doubled int32 `protobuf:"varint,3,opt,name=doubled,proto3" json:"doubled,omitempty"`
}

func (x *DoubleStreamResponse) Reset() {
	*x = DoubleStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bistream_bistream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleStreamResponse) ProtoMessage() {}

func (x *DoubleStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bistream_bistream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleStreamResponse.ProtoReflect.Descriptor instead.
func (*DoubleStreamResponse) Descriptor() ([]byte, []int) {
	return file_bistream_bistream_proto_rawDescGZIP(), []int{1}
}

func (x *DoubleStreamResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DoubleStreamResponse) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *DoubleStreamResponse) GetDoubled() int32 {
	if x != nil {
		return x.Doubled
	}
	return 0
}

var File_bistream_bistream_proto protoreflect.FileDescriptor

var file_bistream_bistream_proto_rawDesc = []byte{
	0x0a, 0x17, 0x62, 0x69, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x62, 0x69, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x62, 0x69, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x22, 0x27, 0x0a, 0x13, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x52, 0x0a, 0x14,
	0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x64,
	0x32, 0x63, 0x0a, 0x0c, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x12, 0x53, 0x0a, 0x0c, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x12, 0x1d, 0x2e, 0x62, 0x69, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x44, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x62, 0x69, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x61, 0x73, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x6c, 0x6f, 0x73, 0x76,
	0x63, 0x64, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x62, 0x69, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_bistream_bistream_proto_rawDescOnce sync.Once
	file_bistream_bistream_proto_rawDescData = file_bistream_bistream_proto_rawDesc
)

func file_bistream_bistream_proto_rawDescGZIP() []byte {
	file_bistream_bistream_proto_rawDescOnce.Do(func() {
		file_bistream_bistream_proto_rawDescData = protoimpl.X.CompressGZIP(file_bistream_bistream_proto_rawDescData)
	})
	return file_bistream_bistream_proto_rawDescData
}

var file_bistream_bistream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bistream_bistream_proto_goTypes = []interface{}{
	(*DoubleStreamRequest)(nil),  // 0: bistream.DoubleStreamRequest
	(*DoubleStreamResponse)(nil), // 1: bistream.DoubleStreamResponse
}
var file_bistream_bistream_proto_depIdxs = []int32{
	0, // 0: bistream.DoubleStream.DoubleStream:input_type -> bistream.DoubleStreamRequest
	1, // 1: bistream.DoubleStream.DoubleStream:output_type -> bistream.DoubleStreamResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bistream_bistream_proto_init() }
func file_bistream_bistream_proto_init() {
	if File_bistream_bistream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bistream_bistream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bistream_bistream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bistream_bistream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bistream_bistream_proto_goTypes,
		DependencyIndexes: file_bistream_bistream_proto_depIdxs,
		MessageInfos:      file_bistream_bistream_proto_msgTypes,
	}.Build()
	File_bistream_bistream_proto = out.File
	file_bistream_bistream_proto_rawDesc = nil
	file_bistream_bistream_proto_goTypes = nil
	file_bistream_bistream_proto_depIdxs = nil
}
