// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: doubleNum/double_num.proto

package doubleNum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoubleNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *DoubleNumRequest) Reset() {
	*x = DoubleNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doubleNum_double_num_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleNumRequest) ProtoMessage() {}

func (x *DoubleNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doubleNum_double_num_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleNumRequest.ProtoReflect.Descriptor instead.
func (*DoubleNumRequest) Descriptor() ([]byte, []int) {
	return file_doubleNum_double_num_proto_rawDescGZIP(), []int{0}
}

func (x *DoubleNumRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type DoubleNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Doubled int32 `protobuf:"varint,1,opt,name=doubled,proto3" json:"doubled,omitempty"`
}

func (x *DoubleNumResponse) Reset() {
	*x = DoubleNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doubleNum_double_num_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleNumResponse) ProtoMessage() {}

func (x *DoubleNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doubleNum_double_num_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleNumResponse.ProtoReflect.Descriptor instead.
func (*DoubleNumResponse) Descriptor() ([]byte, []int) {
	return file_doubleNum_double_num_proto_rawDescGZIP(), []int{1}
}

func (x *DoubleNumResponse) GetDoubled() int32 {
	if x != nil {
		return x.Doubled
	}
	return 0
}

type TripleNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *TripleNumRequest) Reset() {
	*x = TripleNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doubleNum_double_num_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripleNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripleNumRequest) ProtoMessage() {}

func (x *TripleNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doubleNum_double_num_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripleNumRequest.ProtoReflect.Descriptor instead.
func (*TripleNumRequest) Descriptor() ([]byte, []int) {
	return file_doubleNum_double_num_proto_rawDescGZIP(), []int{2}
}

func (x *TripleNumRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type TripleNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tripled int32 `protobuf:"varint,1,opt,name=tripled,proto3" json:"tripled,omitempty"`
}

func (x *TripleNumResponse) Reset() {
	*x = TripleNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doubleNum_double_num_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripleNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripleNumResponse) ProtoMessage() {}

func (x *TripleNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doubleNum_double_num_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripleNumResponse.ProtoReflect.Descriptor instead.
func (*TripleNumResponse) Descriptor() ([]byte, []int) {
	return file_doubleNum_double_num_proto_rawDescGZIP(), []int{3}
}

func (x *TripleNumResponse) GetTripled() int32 {
	if x != nil {
		return x.Tripled
	}
	return 0
}

var File_doubleNum_double_num_proto protoreflect.FileDescriptor

var file_doubleNum_double_num_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x2f, 0x64, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x22, 0x24, 0x0a, 0x10, 0x44, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x2d, 0x0a,
	0x11, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x24, 0x0a, 0x10,
	0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e,
	0x75, 0x6d, 0x22, 0x2d, 0x0a, 0x11, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x69, 0x70, 0x6c,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x69, 0x70, 0x6c, 0x65,
	0x64, 0x32, 0x9f, 0x01, 0x0a, 0x09, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x12,
	0x48, 0x0a, 0x09, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x2e, 0x64,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4e,
	0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x64, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x09, 0x54, 0x72, 0x69,
	0x70, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x2e, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4e,
	0x75, 0x6d, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x2e,
	0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x76, 0x61, 0x73, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x6c, 0x6f, 0x73, 0x76, 0x63, 0x64,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_doubleNum_double_num_proto_rawDescOnce sync.Once
	file_doubleNum_double_num_proto_rawDescData = file_doubleNum_double_num_proto_rawDesc
)

func file_doubleNum_double_num_proto_rawDescGZIP() []byte {
	file_doubleNum_double_num_proto_rawDescOnce.Do(func() {
		file_doubleNum_double_num_proto_rawDescData = protoimpl.X.CompressGZIP(file_doubleNum_double_num_proto_rawDescData)
	})
	return file_doubleNum_double_num_proto_rawDescData
}

var file_doubleNum_double_num_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_doubleNum_double_num_proto_goTypes = []interface{}{
	(*DoubleNumRequest)(nil),  // 0: doubleNum.DoubleNumRequest
	(*DoubleNumResponse)(nil), // 1: doubleNum.DoubleNumResponse
	(*TripleNumRequest)(nil),  // 2: doubleNum.TripleNumRequest
	(*TripleNumResponse)(nil), // 3: doubleNum.TripleNumResponse
}
var file_doubleNum_double_num_proto_depIdxs = []int32{
	0, // 0: doubleNum.DoubleNum.DoubleNum:input_type -> doubleNum.DoubleNumRequest
	2, // 1: doubleNum.DoubleNum.TripleNum:input_type -> doubleNum.TripleNumRequest
	1, // 2: doubleNum.DoubleNum.DoubleNum:output_type -> doubleNum.DoubleNumResponse
	3, // 3: doubleNum.DoubleNum.TripleNum:output_type -> doubleNum.TripleNumResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_doubleNum_double_num_proto_init() }
func file_doubleNum_double_num_proto_init() {
	if File_doubleNum_double_num_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_doubleNum_double_num_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doubleNum_double_num_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doubleNum_double_num_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripleNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doubleNum_double_num_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripleNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_doubleNum_double_num_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doubleNum_double_num_proto_goTypes,
		DependencyIndexes: file_doubleNum_double_num_proto_depIdxs,
		MessageInfos:      file_doubleNum_double_num_proto_msgTypes,
	}.Build()
	File_doubleNum_double_num_proto = out.File
	file_doubleNum_double_num_proto_rawDesc = nil
	file_doubleNum_double_num_proto_goTypes = nil
	file_doubleNum_double_num_proto_depIdxs = nil
}
